// Generated by CoffeeScript 1.6.2
/*
  @author Curtis M. Humphrey, Ph.D.
  
  The files adds a KO binding for Morf
      
  Dependence (from global namespace):
    ko - knockoutjs
    Morf - from Morf (https://github.com/joelambert/morf)
      
  Public API, Fired Events, or Exports
    export on ko as a new binding e.g., data-bind="morf: value"
      where value = css: "", parameters: "" from morf documentation
*/


(function() {
  var has_morf;

  has_morf = '__ko_has_morf';

  ko.bindingHandlers.morf = {
    update: function(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
      var value;

      element[has_morf] = false;
      value = ko.utils.unwrapObservable(valueAccessor());
      if (value) {
        return element[has_morf] = Morf.transition(element, value.css, value.parameters);
      }
    }
  };

}).call(this);
